# Default values for openiam-configmap.
# This is a YAML-formatted file.
ingress:
  enabled: false
openiam:
  cassandra:
    password:
  image:
    environment: "%BUILD_ENVIRONMENT%"
    pullPolicy: "%IMAGE_PULL_POLICY%"
    version: "%OPENIAM_VERSION_NUMBER%"
    prefix: "%DOCKER_IMAGE_PREFIX%"
    credentials:
      registry: "%DOCKER_REGISTRY%"
      username: "%DOCKERHUB_USERNAME%"
      password: "%DOCKERHUB_PASSWORD%"
