@echo off

::Change this based on your requirements
SET BUILD_ENVIRONMENT=qa
SET OPENIAM_VERSION_NUMBER=4.2.1.3
SET OPENIAM_BASH_LOG_LEVEL=warn
SET LOGGING_LEVEL=WARN
SET APP_NAME=i-identity-nonprod

:: Change this by demand. Usually this is what you need.
SET DOCKER_IMAGE_PREFIX=openiamdocker
SET DOCKER_REGISTRY=docker.io
SET DOCKER_REGISTRY_SEPARATOR=/
SET OPENIAM_DB_USERNAME=IAMUSER
SET ACTIVITI_DB_USERNAME=ACTIVITI
SET OPENIAM_DB_NAME=openiam
SET ACTIVITI_DB_NAME=activiti
SET IMAGE_PULL_POLICY=Always
SET ELASTICSEARCH_USERNAME=elastic
::SET DOCKERHUB_USERNAME=DOCKERHUB_USERNAME
::SET DOCKERHUB_PASSWORD=DOCKERHUB_PASSWORD


SET REDIS_CHART_VERSION=17.3.1
SET ELASTICSEARCH_CHART_VERSION=7.16.2
SET MARIADB_CHART_VERSION=10.5.1
SET CONSUL_CHART_VERSION=0.48.0
SET RABBITMQ_CHART_VERSION=10.1.16
SET CASSANDRA_CHART_VERSION=9.2.5

SET FLYWAY_COMMAND=migrate

SET NUM_WORKER_NODES=1

::SET OPEN_SSL_PATH=C:\OpenSSL\bin\openssl.exe

:: these are only used if TLS is enabled in RabbitMQ
SET RABBITMQ_HOST=%APP_NAME%-rabbitmq

:: used for elasticsearch certs
SET ELASTICSEARCH_HOST=elasticsearch-master
SET ELASTICSEARCH_KEY_PASSWORD=passwd00

SET RABBITMQ_USERNAME=openiam

SET SAS_FIRST_PROTOCOL=http
SET SAS_FIRST_SERVER=localhost
SET SAS_FIRST_PORT=80
SET SAS_SECOND_PROTOCOL=http
SET SAS_SECOND_SERVER=""
SET SAS_SECOND_PORT=80

SET GOOGLE_PROJECT=""
