#!/usr/bin/env bash

#Change this based on your requirements
BUILD_ENVIRONMENT="qa"
OPENIAM_VERSION_NUMBER="4.2.1.3"
OPENIAM_BASH_LOG_LEVEL="warn"
APP_NAME="openiam-openshift"
export APP_NAME="openiam-openshift"

# Change this by demand. Usually this is what you need.
DOCKER_IMAGE_PREFIX="openiamdocker"
DOCKER_REGISTRY="docker.io"
DOCKER_REGISTRY_SEPARATOR="/"
OPENIAM_DB_USERNAME="IAMUSER"
ACTIVITI_DB_USERNAME="ACTIVITI"
OPENIAM_DB_NAME="openiam"
ACTIVITI_DB_NAME="activiti"
IMAGE_PULL_POLICY="Always"
ELASTICSEARCH_USERNAME="elastic"

REDIS_CHART_VERSION="17.3.1"
ELASTICSEARCH_CHART_VERSIOn="7.16.2"
MARIADB_CHART_VERSION="10.5.1"
CONSUL_CHART_VERSION="0.48.0"
RABBITMQ_CHART_VERSION="10.1.16"
CASSANDRA_CHART_VERSION="9.2.5"

FLYWAY_COMMAND=migrate

NUM_WORKER_NODES=1

RABBITMQ_USERNAME=openiam

# these are only used if TLS is enabled in RabbitMQ
export RABBITMQ_HOST=${APP_NAME}-rabbitmq

SAS_FIRST_PROTOCOL=http
SAS_FIRST_SERVER=""
SAS_FIRST_PORT=80
SAS_SECOND_PROTOCOL=http
SAS_SECOND_SERVER=""
SAS_SECOND_PORT=80