primary:
  podSecurityContext:
    enabled: false

  containerSecurityContext:
    runAsUser: null

secondary:
  podSecurityContext:
    enabled: false

  containerSecurityContext:
    runAsUser: null