# Default values for openiam.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nfs-server-provisioner:
  storageClass:
    create: false
  persistence:
    enabled: false
ingress:
  enabled: false
openiam:
  vault:
    volume:
      seal:
        annotations: []
        size: '10M'
        accessModes:
        - ReadWriteMany
        storageClass: 'azurefile'
      client:
        annotations: []
        size: '10M'
        accessModes:
        - ReadWriteMany
        storageClass: 'azurefile'
      server:
        annotations: []
        size: '10M'
        accessModes:
        - ReadWriteMany
        storageClass: 'azurefile'
      storage:
        annotations: []
        size: '1Gi'
        accessModes:
        - ReadWriteMany
        storageClass: 'azurefile'
  groovy_manager:
    volume:
      iamscripts:
        annotations: []
        size: '10M'
        accessModes:
        - ReadWriteMany
        storageClass: 'azurefile'
  workflow:
    volume:
      activiti:
        annotations: []
        size: '5M'
        accessModes:
        - ReadWriteMany
        storageClass: 'azurefile'
  ldap_connector_rabbitmq:
    volume:
      ldap_connector_rabbitmq:
        annotations: []
        size: '5M'
        accessModes:
        - ReadWriteMany
        storageClass: 'azurefile'
  rabbitmq:
    volume:
      annotations: []
      size: '5M'
      accessModes:
      - ReadWriteMany
      storageClass: 'azurefile'
  upload:
    volume:
      annotations: [ ]
      size: '2Gi'
      accessModes:
        - ReadWriteMany
      storageClass: 'azurefile'
